artifact_location: /home/paduruvignatejreddy/MainFolder/practice/mlflowArtifactPrac/0
creation_time: 1732782897881
experiment_id: '0'
last_update_time: 1732782897881
lifecycle_stage: active
name: Default
