artifact_uri: /home/paduruvignatejreddy/MainFolder/practice/mlflowArtifactPrac/914364694249454381/ddcf940fb1cf49bca8628edbd628eb5b/artifacts
end_time: 1732783202051
entry_point_name: ''
experiment_id: '914364694249454381'
lifecycle_stage: active
run_id: ddcf940fb1cf49bca8628edbd628eb5b
run_name: bouncy-shrike-874
run_uuid: ddcf940fb1cf49bca8628edbd628eb5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732783199380
status: 3
tags: []
user_id: paduruvignatejreddy
